name       : rcm
version    : 1.3.0
release    : 1
source     :
    - https://thoughtbot.github.io/rcm/dist/rcm-1.3.0.tar.gz : ddcf638b367b0361d8e063c29fd573dbe1712d1b83e8d5b3a868e4aa45ffc847
license    : BSD-3-Clause
component  : system.util
summary    : RC (dot-file) management
description: |
    A suite of tools for managing dot-files (.zshrc, .vimrc, etc.).  This suite is useful for committing your .*rc files to a central repository to share, but it also scales to a more complex situation such as multiple source directories shared between computers with some host-specific or task-specific files.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
