name       : rcm
version    : 1.3.1
release    : 2
source     :
    - https://github.com/thoughtbot/rcm/archive/v1.3.1.tar.gz : b88bf859f221b88022a2d3cb2c740778e3d4f2591c25d0e7e5ce70829c2ed9db
license    : BSD-3-Clause
component  : system.util
summary    : RC (dot-file) management
description: |
    A suite of tools for managing dot-files (.zshrc, .vimrc, etc.).  This suite is useful for committing your .*rc files to a central repository to share, but it also scales to a more complex situation such as multiple source directories shared between computers with some host-specific or task-specific files.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
