name       : rcm
version    : 1.3.6
release    : 7
source     :
    - https://github.com/thoughtbot/rcm/releases/download/v1.3.6/rcm-1.3.6.tar.gz : f4fdfbc451d1fb5764531290a202a0a871f6b81ba3c01a6b76c49435c85080a5
license    : BSD-3-Clause
component  : system.util
summary    : RC (dot-file) management
description: |
    A suite of tools for managing dot-files (.zshrc, .vimrc, etc.). This suite is useful for committing your .*rc files to a central repository to share, but it also scales to a more complex situation such as multiple source directories shared between computers with some host-specific or task-specific files.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

