name       : rcm
version    : 1.3.5
release    : 6
source     :
    - https://github.com/thoughtbot/rcm/releases/download/v1.3.5/rcm-1.3.5.tar.gz : 91aeae8eb97e36432dcedcb81337c1a1caeabc0f3e9a3509b7a1740b225af016
license    : BSD-3-Clause
component  : system.util
summary    : RC (dot-file) management
description: |
    A suite of tools for managing dot-files (.zshrc, .vimrc, etc.). This suite is useful for committing your .*rc files to a central repository to share, but it also scales to a more complex situation such as multiple source directories shared between computers with some host-specific or task-specific files.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

