name       : rcm
version    : 1.3.4
release    : 4
source     :
    - git|https://github.com/thoughtbot/rcm.git : v1.3.4
license    : BSD-3-Clause
component  : system.util
summary    : RC (dot-file) management
description: |
    A suite of tools for managing dot-files (.zshrc, .vimrc, etc.).  This suite is useful for committing your .*rc files to a central repository to share, but it also scales to a more complex situation such as multiple source directories shared between computers with some host-specific or task-specific files.
builddeps  :
    - ruby-mustache
    - git
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-building-with-solbuild.patch
    %autogen
build      : |
    %make
install    : |
    %make_install

